### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by Ronmi** [yurenju/wallbox#21]
wallbox.py throws two relative exceptions, and stop running further.
When first running (or clear ~/.local/wallbox before running) it shows tray icon correctly while wizard setting it up. After that, it throws two dbus exception and stop running. I can still close it with pop-up menu in tray, but nothing else runs.

Here're exceptions:

```
ERROR:dbus.service:Unable to append ({u'source': 56212371378, u'message': u'
\u53bb\u5927\u8cb7\u5bb6\u88dc\u8ca8\u56de\u4f86\u591a\u4e8612\u689d\u7559\u
8a00\u56e7 \u611f\u8b1d\u5404\u4f4d', u'uid': 1377620908, u'status_id': 2824
24927740},) to message with signature a{sv}: <type 'exceptions.OverflowError
'>: Value 377796530 out of range for Int32
Traceback (most recent call last):
  File "./wallbox.py", line 227, in <module>
    run_wallbox ()
  File "./wallbox.py", line 223, in run_wallbox
    w = wallbox ()
  File "./wallbox.py", line 58, in __init__
    self.make_ui ()
  File "./wallbox.py", line 98, in make_ui
    self.notification = notification.Notification ()
  File "/home/ronmi/self/wallbox/src/wallbox/notification.py", line 62, in __init__
    self.view_refresh ()
  File "/home/ronmi/self/wallbox/src/wallbox/notification.py", line 292, in view_refresh
    self.refresh_current_status ()
  File "/home/ronmi/self/wallbox/src/wallbox/notification.py", line 132, in refresh_current_status
    status = self.office.get_current_status ()
  File "/usr/lib/pymodules/python2.6/dbus/proxies.py", line 140, in __call__
    **keywords)
  File "/usr/lib/pymodules/python2.6/dbus/connection.py", line 620, in call_blocking
    message, timeout)


dbus.exceptions.DBusException: org.freedesktop.DBus.Python.OverflowError: Tr
aceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/dbus/service.py", line 745, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/pymodules/python2.6/dbus/service.py", line 252, in _method_reply_return
    reply.append(signature=signature, *retval)
OverflowError: Value 377796530 out of range for Int32
```

**Comment by Ronmi** [comment]
same problem with v0.4 http://gist.github.com/333538
