### ISSUE TITLE
cannot  show  notifications and icon, only my recent status 

### ISSUE THREAD

**Issue by rezzafr33** [yurenju/wallbox#24]
Wallbox doesn't show my icon and notifications, i got this message:

<PRE><CODE>INFO:root:get remote comments (fast)
DEBUG:root:_query: SELECT source_id, post_id, message, permalink FROM stream WHERE 
DEBUG:root:notification_mark_all_read
DEBUG:root:no need to notification mark all read
DEBUG:root:URLError, Sleep 3 sec: SELECT source_id, post_id, message, permalink FROM stream WHERE 
DEBUG:root:URLError, Sleep 3 sec: SELECT source_id, post_id, message, permalink FROM stream WHERE 
DEBUG:root:URLError, Sleep 3 sec: SELECT source_id, post_id, message, permalink FROM stream WHERE 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 525, in __bootstrap_inner
    self.run()
  File "/usr/lib/pymodules/python2.6/wallbox/post_office.py", line 383, in run
    self.get_remote_comments ()
  File "/usr/lib/pymodules/python2.6/wallbox/post_office.py", line 217, in get_remote_comments
    if len (result) < len (subquery):
TypeError: object of type 'NoneType' has no len()</CODE></PRE>

**Comment by yohripnj** [comment]
same error as me T_T

**Comment by rezzafr33** [comment]
Upgrade to lucid, but unfortunately no fix, ...
